baseURL = "https://jonathanold.github.io/"
relativeURLs = true
title = "Jonathan Old"
theme = ["academimal"]
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" , "make.sh"]

[params]
    shortbio = "Ph.D. candidate in economics at UC Berkeley, on the job market in 2026–27. Political economy and development economics."
    logo = "jold_portrait_ucv.jpg" 
    author = "Jonathan Old"
    sitename = "Personal website of Jonathan Old"
    

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  